---
apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: {{ include "pod-add-image-pull-secret.fullname" . }}-certs
spec:
  secretName: {{ include "pod-add-image-pull-secret.fullname" . }}-certs
  duration: 8760h  # 1 year
  dnsNames:
  - {{ include "pod-add-image-pull-secret.fullname" . }}
  - {{ include "pod-add-image-pull-secret.fullname" . }}.{{ .Release.Namespace }}
  - {{ include "pod-add-image-pull-secret.fullname" . }}.{{ .Release.Namespace }}.svc
  issuerRef:
    name: selfsigned

---
apiVersion: cert-manager.io/v1alpha3
kind: Issuer
metadata:
  name: selfsigned
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
