{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pod-add-image-pull-secret.serviceAccountName" . }}
  labels:
    {{- include "pod-add-image-pull-secret.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "pod-add-image-pull-secret.serviceAccountName" . }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "pod-add-image-pull-secret.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "pod-add-image-pull-secret.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "pod-add-image-pull-secret.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
