---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "pod-add-image-pull-secret.fullname" . }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "pod-add-image-pull-secret.fullname" . }}-certs
webhooks:
- name: {{ include "pod-add-image-pull-secret.fullname" . }}.k8s-webhooks.xeed.io
  admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: {{ include "pod-add-image-pull-secret.fullname" . }}
      namespace: {{ .Release.Namespace }}
      path: /mutate
      port: 443
  failurePolicy: Ignore
  matchPolicy: Exact
  rules:
    - operations: ["CREATE"]
      apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
  sideEffects: None
